### ISSUE TITLE
[BUG] Erro quando itmax é maior do que 1000 e n_historico não é definido

### ISSUE THREAD

**Issue by caiqueaf** [ddss/PSO#13]
raise ValueError('O tamanho do histórico está incompatível com o número de iterações. n_historico ({}) deve ser dividor de itmax({})-init_historico({})'.format(self.n_historico,itmax,self.init_historico))
ValueError: O tamanho do histórico está incompatível com o número de iterações. n_historico (1000) deve ser dividor de itmax(1500)-init_historico(0)

**Comment by ddss** [comment]
Acredito que seja um erro na definição do valor default de n_historico

**Comment by ddss** [comment]
Corrigido no commit c748ecc9bacab9b6b9449aa6020ff81f93cd4b2d
